# Laszlo Cseh vs Michael Phelps

In this notebook we will be analyzing the careers of Michael Phelps and Laszlo Cseh.

#### Step 1 Loading Datasets
We will start off by getting the data from the web, and altering the columns to match what we want.

In [33]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

url = "https://api.worldaquatics.com/fina/athletes/1001621/results"
headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "application/json"
}

response = requests.get(url, headers=headers)
data = response.json()

# Convert to pandas DataFrame
michael_Phelps = pd.DataFrame(data["Results"])

michael_Phelps.head(3)

,Rank,MedalTag,SportCode,DisciplineName,PhaseName,RecordType,NAT,CompetitionName,CompetitionType,CompetitionCountry,CompetitionCity,Date,Time,UtcDateTime,Points,Tags,AthleteResultAge
0,1.0,G,SW,Men 4x100m Medley Relay,Finals,OR,USA,Olympic Games Rio 2016,Olympic Games,BRA,Rio de Janeiro,2016-08-13,3:27.95,2016-08-14T02:04:00,990.0,None,31
1,2.0,S,SW,Men 100m Butterfly,Finals,,USA,Olympic Games Rio 2016,Olympic Games,BRA,Rio de Janeiro,2016-08-12,51.14,2016-08-13T01:12:00,924.0,None,31
2,1.0,G,SW,Men 200m Medley,Finals,,USA,Olympic Games Rio 2016,Olympic Games,BRA,Rio de Janeiro,2016-08-11,1:54.66,2016-08-12T02:01:00,982.0,None,31

In [34]:
import requests
import pandas as pd

url = "https://api.worldaquatics.com/fina/athletes/1007320/results"
headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "application/json"
}

response = requests.get(url, headers=headers)
data = response.json()

# Convert to pandas DataFrame
laszlo_Cseh = pd.DataFrame(data["Results"])

laszlo_Cseh.head(3)

,Rank,MedalTag,SportCode,DisciplineName,PhaseName,RecordType,NAT,CompetitionName,CompetitionType,CompetitionCountry,CompetitionCity,Date,Time,UtcDateTime,Points,Tags,AthleteResultAge,ClubName
0,7.0,None,SW,Men 200m Medley,Finals,,HUN,Olympic Games Tokyo 2020,Olympic Games,JPN,Tokyo,2021-07-30,1:57.68,2021-07-30T02:20:15,909.0,None,35,NaN
1,2.0,None,SW,Men 200m Freestyle,Finals,,HUN,Budapest Open Championships,Open,HUN,Budapest,2021-06-19,1:49.34,NaN,811.0,None,35,Budapesti Vasutas Sport Club
2,2.0,None,SW,Men 100m Butterfly,Finals,,HUN,Budapest Open Championships,Open,HUN,Budapest,2021-06-19,52.57,NaN,834.0,None,35,Budapesti Vasutas Sport Club

In [35]:
michael_Phelps = michael_Phelps.rename(columns={
    "Rank": "Overall Rank",
    "DisciplineName": "Event",
    "Time": "Time",
    "Points": "Points",
    "Tags": "Tag",
    "AthleteResultAge": "Age",
    "CompetitionName": "Competition",
    "CompetitionCountry": "Comp Country",
    "Date": "Date"
})

michael_Phelps = michael_Phelps[
    ["Overall Rank", "Event", "Time", "Age", "Competition", "Comp Country", "Date"]
]
michael_Phelps.head(3)

,Overall Rank,Event,Time,Age,Competition,Comp Country,Date
0,1.0,Men 4x100m Medley Relay,3:27.95,31,Olympic Games Rio 2016,BRA,2016-08-13
1,2.0,Men 100m Butterfly,51.14,31,Olympic Games Rio 2016,BRA,2016-08-12
2,1.0,Men 200m Medley,1:54.66,31,Olympic Games Rio 2016,BRA,2016-08-11

In [36]:
laszlo_Cseh = laszlo_Cseh.rename(columns={
    "Rank": "Overall Rank",
    "DisciplineName": "Event",
    "Time": "Time",
    "Points": "Points",
    "Tags": "Tag",
    "AthleteResultAge": "Age",
    "CompetitionName": "Competition",
    "CompetitionCountry": "Comp Country",
    "Date": "Date"
})

laszlo_Cseh = laszlo_Cseh[
    ["Overall Rank", "Event", "Time", "Age", "Competition", "Comp Country", "Date"]
]
laszlo_Cseh.head(3)

,Overall Rank,Event,Time,Age,Competition,Comp Country,Date
0,7.0,Men 200m Medley,1:57.68,35,Olympic Games Tokyo 2020,JPN,2021-07-30
1,2.0,Men 200m Freestyle,1:49.34,35,Budapest Open Championships,HUN,2021-06-19
2,2.0,Men 100m Butterfly,52.57,35,Budapest Open Championships,HUN,2021-06-19

In [ ]:
michael_Phelps["Date"] = pd.to_datetime(michael_Phelps["Date"])


def time_to_seconds(t):
    if pd.isna(t):
        return np.nan
    if isinstance(t, str):
        t = t.strip()
        if t in ["DNS", "DNF", "DSQ"]:
            return np.nan
        if ":" in t:
            m, s = t.split(":")
            return int(m) * 60 + float(s)
    return float(t)

michael_Phelps["Time_seconds"] = michael_Phelps["Time"].apply(time_to_seconds)

event_name = "Men 200m Medley"
event_michael_Phelps= michael_Phelps[michael_Phelps["Event"] == event_name].sort_values("Date")

sns.set(style="whitegrid")

plt.figure(figsize=(8, 5))
sns.lineplot(
    data=event_michael_Phelps,
    x="Date",
    y="Time_seconds",
    marker="o"
)

plt.title(f"Performance Progression Over Time\n{event_name}")
plt.xlabel("Date")
plt.ylabel("Time (seconds)")
plt.gca().invert_yaxis()  # faster times appear higher
plt.tight_layout()
plt.show()

ValueError: could not convert string to float: 'DNS'